name: Command - deploy

#
# An IssueOps Command. This command provides a "/deploy <env>" command that can be used from Issue comments
# This is very similar to a Slack Slash command in intent.
#

on:
  issue_comment:
    types:
      - created
      - edited

jobs:
  command:
    name: Command
    runs-on: ubuntu-20.04

    # Save some actions minutes, and only execute when necessary :-)
    if: startsWith(github.event.comment.body, '/deploy ')

    steps:
      - name: Get temporary token
        id: temp_token
        uses: peter-murray/workflow-application-token-action@v1
        with:
          application_id: ${{ secrets.OCTODEMOBOT_APPLICATION_ID_REPO_AUTOMATION }}
          application_private_key: ${{ secrets.OCTODEMOBOT_APPLICATION_KEY_REPO_AUTOMATION }}

      - name: Parse and Respond to Command
        uses: actions/github-script@v3
        with:
          github-token: ${{ steps.temp_token.outputs.token }}
          script: |
            const comment = context.payload.comment.body;
            const request = /\/deploy (.*)/.exec(comment);
            const ALLOWED_ENVIRONMENTS = ['qa', 'test'];
            // Ensure request is one of the allowed options
            if (request && ALLOWED_ENVIRONMENTS.indexOf(request[1]) > -1) {
              console.log(`deploy request for environment "${request[1]}"`);

              await github.issues.addLabels({
                ...context.repo,
                issue_number: context.issue.number,
                labels: [`Deploy to ${request[1]}`]
              });
            } else {
              console.log(`:red_circle:  Unsupported deployment request to environment "${request ? request[1] : null}"`);
            }
